### ISSUE TITLE
No files

### ISSUE THREAD

**Issue by SchnitzyNine** [cosmohacker/SpoytifDownloadManager#6]
So when I entered this link: https://open.spotify.com/artist/0Ca8QNi2jA2pemnFC6Rydj
and selected the output folder and clicked download nothing happens, the terminal below shows download completed and the folder itself has only one file in it.

![image](https://user-images.githubusercontent.com/127578465/234518441-ee2f90e5-dbda-4efb-99e1-38683d33f7e1.png)
![image](https://user-images.githubusercontent.com/127578465/234518484-82c7f504-74de-4505-bdda-a2b466248160.png)

**Comment by cosmohacker** [comment]
Yah, it can happen on some computers.(i m not good at setup phase :(  )
You need to check whether "pip" is installed in the terminal by typing "pip help", if not, you can see how to install it from this link.

https://www.geeksforgeeks.org/how-to-install-pip-on-windows/

By the way, you need to have python installed on your computer.

After that you can download songs without any errors.

**Comment by SchnitzyNine** [comment]
> Yah, it can happen on some computers.(i m not good at setup phase :( ) You need to check whether "pip" is installed in the terminal by typing "pip help", if not, you can see how to install it from this link.
> 
> https://www.geeksforgeeks.org/how-to-install-pip-on-windows/
> 
> By the way, you need to have python installed on your computer.
> 
> After that you can download songs without any errors.

I do have pip installed and in path and the latest version of python installed on path

**Comment by cosmohacker** [comment]
could you send me a screenshot of result after typed powershell spotdl or python -m spotdl ?

**Comment by SchnitzyNine** [comment]
> could you send me a screenshot of result after typed powershell spotdl or python -m spotdl ?

Can we chat on discord or somewhere?
![image](https://user-images.githubusercontent.com/127578465/234525160-5c54752d-1055-4773-88f1-6f9e15e9a452.png)
![image](https://user-images.githubusercontent.com/127578465/234525282-069bbc1c-a0d1-4eca-9b23-bc97dc89d263.png)

**Comment by cosmohacker** [comment]
yes sure
https://discord.gg/5wWWfeaN

**Comment by cosmohacker** [comment]
Update spotdl by this command:

pip install --upgrade spotdl

try it again in terminal or in sputyif.exe if the errors occurres you can use this code in powershell

spotdl --manual "song name"

its a bug about package that use to download song from spotify which can be require to use vpn

"Spotify may block downloads from certain regions or IP addresses. Using a VPN may help bypass such restrictions."

in some cases you need to degrade spotdl package by uninstalling:
pip uninstall spodtl
and installing:
pip install spotdl==4.1.3

**Comment by SchnitzyNine** [comment]
For this program to work check if https://music.youtube.com/ is available in your country, if not using a VPN solves the issue! Cheers!
